/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        text: {
          readable: "hsl(var(--secondary-text))",
          subtle: "hsl(var(--tertiary-text))",
          description: "hsl(var(--muted-foreground))",
        },
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        display: ['DM Sans', 'Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
      },
      fontSize: {
        'display-large': ['clamp(3.5rem, 8vw, 6rem)', { lineHeight: '1.1', letterSpacing: '-0.025em' }],
        'display': ['clamp(2.5rem, 6vw, 4rem)', { lineHeight: '1.2', letterSpacing: '-0.02em' }],
        'headline-large': ['clamp(2rem, 4vw, 3rem)', { lineHeight: '1.25', letterSpacing: '-0.015em' }],
        'headline': ['clamp(1.5rem, 3vw, 2.25rem)', { lineHeight: '1.3', letterSpacing: '-0.01em' }],
        'title-large': ['1.375rem', { lineHeight: '1.4', letterSpacing: '-0.005em' }],
        'title': ['1.125rem', { lineHeight: '1.4', letterSpacing: '-0.005em' }],
        'body-large': ['1.125rem', { lineHeight: '1.6', letterSpacing: '0' }],
        'body': ['1rem', { lineHeight: '1.6', letterSpacing: '0' }],
        'body-small': ['0.875rem', { lineHeight: '1.5', letterSpacing: '0.005em' }],
        'label-large': ['0.875rem', { lineHeight: '1.4', letterSpacing: '0.01em' }],
        'label': ['0.75rem', { lineHeight: '1.4', letterSpacing: '0.015em' }],
        'label-small': ['0.6875rem', { lineHeight: '1.3', letterSpacing: '0.02em' }],
      },
      borderRadius: {
        'none': '0',
        'sm': 'var(--radius-sm)',
        'DEFAULT': 'var(--radius)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        'full': 'var(--radius-full)',
      },
      boxShadow: {
        'none': 'var(--elevation-0)',
        'sm': 'var(--elevation-1)',
        'DEFAULT': 'var(--elevation-2)',
        'md': 'var(--elevation-3)',
        'lg': 'var(--elevation-4)',
        'xl': 'var(--elevation-5)',
      },
      spacing: {
        '0': 'var(--space-0)',
        '1': 'var(--space-1)',
        '2': 'var(--space-2)',
        '3': 'var(--space-3)',
        '4': 'var(--space-4)',
        '5': 'var(--space-5)',
        '6': 'var(--space-6)',
        '8': 'var(--space-8)',
        '10': 'var(--space-10)',
        '12': 'var(--space-12)',
        '16': 'var(--space-16)',
        '20': 'var(--space-20)',
        '24': 'var(--space-24)',
        '32': 'var(--space-32)',
      },
      transitionDuration: {
        'short1': 'var(--motion-duration-short1)',
        'short2': 'var(--motion-duration-short2)',
        'short3': 'var(--motion-duration-short3)',
        'short4': 'var(--motion-duration-short4)',
        'medium1': 'var(--motion-duration-medium1)',
        'medium2': 'var(--motion-duration-medium2)',
        'medium3': 'var(--motion-duration-medium3)',
        'medium4': 'var(--motion-duration-medium4)',
      },
      transitionTimingFunction: {
        'standard': 'var(--motion-easing-standard)',
        'emphasized': 'var(--motion-easing-emphasized)',
        'decelerated': 'var(--motion-easing-standard-decelerate)',
        'accelerated': 'var(--motion-easing-standard-accelerate)',
      },
      backgroundImage: {
        'mandala': "radial-gradient(circle at 25% 25%, rgba(109, 40, 217, 0.1) 0%, transparent 50%), radial-gradient(circle at 75% 75%, rgba(37, 99, 235, 0.1) 0%, transparent 50%)",
      },
    },
  },
  plugins: [],
}